title: "AWS"
summary: "AWSのサマリ"
topics: [aws]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - what-is-aws
  - region
  - iam
  - vpc
  - security-group
  - ec2
  - lambda
