title: "単体テストの考え方/使い方"
summary: "変化に強いソフトウェアを作り続けるために"
topics: [testing]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - initial
  - what-do-unit-test
  - unit-test-definition
  - structure-of-unit-test
  - the-four-pillars-of-effective-unit-testing
  - test-double
  - assert-of-behavior
  - how-to-write-testable-production-code
